[B-37655]:Added obligations data to context
infobloxopen/atlas-authz-middleware pull request #1
Opened 2021-01-07 15:45 UTC by singhs1

Added obligations data to context (if present)

2021-01-07 16:39 UTC, drewwells commented on grpc_opa/authorizer.go
> +	if ob,ok := response["obligations"].([]string);ok{
can you run this through go fmt? Apparently we don't check for that on build right now.

2021-01-07 16:42 UTC, drewwells commented on grpc_opa/authorizer.go
> +		ctx = context.WithValue(ctx,"obligations",ob)
change "obligations" to a private type. See this as an example https://github.com/Infoblox-CTO/atlas.eventing/pull/31/files#diff-c553b059ae0d06bffc1383e72286221924a201e5dc96029dc3b4c9174e46ad93R56

2021-01-07 16:43 UTC, drewwells commented on grpc_opa/authorizer.go
> +		ctx = context.WithValue(ctx,"obligations",ob)
The struct{} usage here is a bit unique. An approach I see more often is this
```
type key obligationKey = "obligations"

ctx := context.WithValue(key, ....)
```

2021-01-08 17:16 UTC, drewwells approved these changes
lgtm

2021-01-08 17:20 UTC, rchowinfoblox requested changes
Shouldn't we capitalize obligationKey and obKey so they're exported to allow other apps to use?

2021-01-08 18:01 UTC, singhs1 commented
> Shouldn't we capitalize obligationKey and obKey so they're exported to allow other apps to use?

Done

2021-01-08 18:02 UTC, rchowinfoblox approved these changes

2021-01-11 11:55 UTC, merged