[Do Not Merge]move shared functionality b/w http and grpc to common folder
infobloxopen/atlas-authz-middleware pull request #29
Opened 2024-01-24 07:55 UTC by cbarik-infoblox

To introduce an HTTP middleware which will authorise the incoming HTTP request by calling OPA sidecar, 
this PR aims to move the code that can be reused by the middleware to a common folder.
`Authorizer` interface will be custom implemented by `GRPC Authorizer` and `HTTP Authorizer`.
For the sake of being less intrusive, `GRPC Authorizer` is still named as `DefaultAuthorizer` as per the existing implementation.
All the grpc specific code will stay in `grpc_opa` folder, while the common code will move to `common` and its children folders.
![image](https://github.com/infobloxopen/atlas-authz-middleware/assets/154232025/6eb09b94-a53b-40bb-af7a-2a1e8676a554)

2024-01-24 11:18 UTC, kanaksinghal commented on common/authorizer/authorizer.go
> +	Evaluate(ctx context.Context, fullMethod string, grpcReq interface{}, opaEvaluator OpaEvaluator) (bool, context.Context, error)
should we get rid of the "grpc" word references here?

2024-01-30 20:54 UTC, rchowinfoblox requested changes
While this code re-organization is good, atlas-authz-middleware is used by practically EVERY Infoblox microservice.  Moving the exported public API to different packages would break compatibility and force app-teams to expend effort to resolve if they upgrade their atlas-authz-middleware.

One suggestion is to put your re-organized code under a top-level atlas-authz-middleware/v2/ directory, and any new features will be under /v2/.  But this also means we have to maintain two separate versions of the middleware.

@drewwells @kumaya any comments on this?

2024-02-01 10:43 UTC, kumaya commented
> While this code re-organization is good, atlas-authz-middleware is used by practically EVERY Infoblox microservice. Moving the exported public API to different packages would break compatibility and force app-teams to expend effort to resolve if they upgrade their atlas-authz-middleware.
> 
> One suggestion is to put your re-organized code under a top-level atlas-authz-middleware/v2/ directory, and any new features will be under /v2/. But this also means we have to maintain two separate versions of the middleware.
> 
> @drewwells @kumaya any comments on this?

Any service that is implementing `Authorizer` interface will need to upgrade the path if they choose to import the new release.
We can ~maintain~ create 2 versions, but would highly recommend to call out v1 (existing) as deprecated. So as to use any new functionality clients will be forced to upgrade the version; they can continue using the existing functionality without breaking things; and dev efforts will be saved maintaining 2 versions.

2024-02-01 13:15 UTC, cbarik-infoblox commented
> While this code re-organization is good, atlas-authz-middleware is used by practically EVERY Infoblox microservice. Moving the exported public API to different packages would break compatibility and force app-teams to expend effort to resolve if they upgrade their atlas-authz-middleware.
> 
> One suggestion is to put your re-organized code under a top-level atlas-authz-middleware/v2/ directory, and any new features will be under /v2/. But this also means we have to maintain two separate versions of the middleware.
> 
> @drewwells @kumaya any comments on this?

@kumaya @rchowinfoblox  @drewwells raised a new PR https://github.com/infobloxopen/atlas-authz-middleware/pull/30/files

2024-02-08 05:18 UTC, closed without merging